language: node_js
branches:
  except:
    - gh-pages
node_js:
  - 0.10
  - 0.12
  - 4
  - iojs
script:
#  - 'npm run cover && cat coverage/lcov.info | npm run cover:up'
  - npm test
notifications:
  email: false
