language: node_js
branches:
  except:
    - gh-pages
node_js:
  - 0.10
  - 0.12
  - 4
  - iojs
before_script:
  - npm run tsc
script:
  - npm run cover
after_success:
  - npm run cover:up
notifications:
  email: false
