language: node_js
branches:
  except:
    - gh-pages
node_js:
  - 4
  - 5
  - 6
  - 7
before_script:
  - npm run tsc
script:
  - npm run cover
after_success:
  - npm run cover:up
notifications:
  email: false
